---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list: ["recipe[shells]"]
    attributes:
      shells:
        packages:
          - bash
          - tcsh
          - ksh
          - zsh
        symlinks:
          '/usr/local/shells/bash': '/bin/bash'
